language: java
jdk:
  - oraclejdk11

script:
  - mvn package
  - java -jar target/http-server-1.0.jar &
  - cd acceptance
  - bundle install
  - bundle exec spinach
  - kill %1
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)